"""adding column is_active in user table

Revision ID: 212ec8f58473
Revises: e6178c104b21
Create Date: 2023-11-10 15:39:33.935858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212ec8f58473'
down_revision = 'e6178c104b21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'is_active')
    # ### end Alembic commands ###
